#!/usr/bin/env python3
"""Render and stage scorecards from a completed Run_verobs_all invocation."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import sys

from scorecard_joint_scores_txt import read_export, render_export


DOMAINS = {
    "SURF": ("surface", "Surface"),
    "TEMP": ("upper_air", "Upper-Air"),
}


def _words(value: str) -> list[str]:
    return value.split()


def _period_label(period: int) -> str:
    return "Whole period" if period == 0 else str(period)


def _load_context_files(
    root: Path, domain: str
) -> dict[tuple[int, int, int], tuple[Path, dict[str, str], list[dict]]]:
    found: dict[tuple[int, int, int], tuple[Path, dict[str, str], list[dict]]] = {}
    for path in sorted((root / domain).glob("joint_scores_*.txt")):
        metadata, rows, _ = read_export(path)
        if metadata.get("domain", "").upper() != domain:
            continue
        expected = {
            "station_scope": "0",
            "selection": "ALL",
            "initial_time_group": "ALL",
        }
        if any(metadata.get(key) != value for key, value in expected.items()):
            continue
        try:
            reference = int(metadata["reference_index"])
            comparison = int(metadata["comparison_index"])
            period = int(metadata["period"])
        except (KeyError, ValueError) as exc:
            raise ValueError(f"{path}: missing or invalid comparison context metadata") from exc
        key = (reference, comparison, period)
        if key in found:
            raise ValueError(f"duplicate export context {key}: {found[key][0]} and {path}")
        found[key] = (path, metadata, rows)
    return found


def _write_input_js(
    entry_dir: Path,
    domains: list[str],
    comparisons: list[tuple[int, str]],
    periods: list[int],
) -> None:
    parameter_values = [f"scorecard_{DOMAINS[domain][0]}" for domain in domains]
    parameter_labels = [DOMAINS[domain][1] for domain in domains]
    comparison_values = [value for value, _ in comparisons]
    comparison_labels = [label for _value, label in comparisons]

    lines = [
        "// Generated by Monitor's scorecard stage.",
        "title = 'Monitor Scorecards';",
        "framec = 'Tomato';",
        f"v[0] = {json.dumps(parameter_values)};",
        f"t[0] = {json.dumps(parameter_labels)};",
        f"v[1] = {json.dumps(comparison_values)};",
        f"t[1] = {json.dumps(comparison_labels)};",
    ]
    if len(periods) > 1:
        period_values = [f"period{period}" for period in periods]
        period_labels = [_period_label(period) for period in periods]
        lines.extend([
            f"v[2] = {json.dumps(period_values)};",
            f"t[2] = {json.dumps(period_labels)};",
            "mname = ['Parameter','Experiment','Period'];",
            "spec_name = [0,1,2];",
            "loc = ['l','l','l'];",
            "msep[2] = '_';",
        ])
    else:
        lines.extend([
            "mname = ['Parameter','Experiment'];",
            "spec_name = [0,1];",
            "loc = ['l','l'];",
        ])
    lines.extend([
        "msep[0] = '_';",
        "msep[1] = '_';",
        "pdir = 'Scorecards/';",
        "ext = 'png';",
        "show_csv_link = true;",
        "help = 'The first experiment is the reference and is compared with each remaining EXP. "
        "Values show reference-minus-comparison normalized RMSE in percent; positive means the comparison has lower RMSE. "
        "Significant values set the colour scale; larger values saturate at its endpoints. "
        "A black outline marks significance at the configured confidence level. "
        "Footer counts show positive and negative squares, for significant squares and for all squares.';",
        "hide_help = false;",
        "do_send = true;",
        "do_show_remember = true;",
        "do_remember = true;",
    ])
    target = entry_dir / "input.js"
    temporary = entry_dir / ".input.js.tmp"
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.replace(temporary, target)


def build(args: argparse.Namespace) -> int:
    experiments = _words(args.experiments)
    display_names = _words(args.display_names) or experiments
    if len(experiments) < 2:
        print("Scorecards omitted: fewer than two experiments are configured.")
        return 0
    if len(display_names) != len(experiments):
        raise ValueError("EXP and DISPLAY_EXP must contain the same number of names")
    if len(set(display_names)) != len(display_names):
        raise ValueError("DISPLAY_EXP contains duplicate names; scorecard choices would be ambiguous")
    reference_index = 1
    pairs = [
        (index, f"ref{reference_index}_exp{index}",
         f"{display_names[reference_index - 1]} vs {display_names[index - 1]}")
        for index in range(1, len(experiments) + 1)
        if index != reference_index
    ]
    enabled_domains = [
        domain for domain, parameter_text in (("SURF", args.surface_parameters), ("TEMP", args.upper_air_parameters))
        if parameter_text.strip()
    ]
    if not enabled_domains:
        print("Scorecards omitted: no surface or upper-air parameters are selected.")
        return 0

    contexts = {domain: _load_context_files(args.stage, domain) for domain in enabled_domains}
    periods_by_domain: dict[str, set[int]] = {}
    for domain in enabled_domains:
        period_set: set[int] = set()
        for index, _pair_key, _label in pairs:
            path_by_period = {
                period: export for (ref, cmp, period), export in contexts[domain].items()
                if ref == reference_index and cmp == index
            }
            if not path_by_period:
                raise ValueError(
                    f"missing {domain} ALL-selection, all-station, ALL-initial export "
                    f"for reference {reference_index} vs experiment {index}"
                )
            period_set.update(path_by_period)
        periods_by_domain[domain] = period_set
    periods = sorted(set.union(*periods_by_domain.values()))
    if any(values != set(periods) for values in periods_by_domain.values()):
        raise ValueError(f"SURF and TEMP exports do not have matching periods: {periods_by_domain}")
    if args.period_type == 1 and periods != [0]:
        raise ValueError(f"PERIOD_TYPE=1 expects aggregate period 0; found {periods}")

    entry_dir = args.outdir
    if entry_dir.exists():
        raise FileExistsError(f"fresh scorecard staging directory already exists: {entry_dir}")
    data_dir = entry_dir / "data"
    data_dir.mkdir(parents=True)

    for domain in enabled_domains:
        domain_name = DOMAINS[domain][0]
        for index, pair_key, label in pairs:
            for period in periods:
                loaded_export = contexts[domain].get((reference_index, index, period))
                if loaded_export is None:
                    raise ValueError(
                        f"missing {domain} export for comparison {pair_key}, period {period}"
                    )
                export, metadata, rows = loaded_export
                period_suffix = f"_period{period}" if (len(periods) > 1 or args.period_type > 1) else ""
                stem = f"scorecard_{domain_name}_ref{reference_index}_exp{index}{period_suffix}"
                shutil.copy2(export, data_dir / export.name)
                render_export(
                    export, metadata, rows, entry_dir, domain,
                    display_names[reference_index - 1], display_names[index - 1],
                    stem, args.levels,
                )

    comparison_menu = []
    for _, pair_key, label in pairs:
        if len(periods) == 1 and args.period_type > 1:
            pair_key = f"{pair_key}_period{periods[0]}"
        comparison_menu.append((pair_key, label))
    _write_input_js(entry_dir, enabled_domains, comparison_menu, periods)
    expected_images = len(enabled_domains) * len(pairs) * len(periods)
    actual_images = list(entry_dir.glob("scorecard_*.png"))
    if len(actual_images) != expected_images:
        raise RuntimeError(f"expected {expected_images} images, found {len(actual_images)}")
    print(f"Staged {expected_images} scorecard images and {len(list(data_dir.iterdir()))} text exports.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", type=Path, required=True)
    parser.add_argument("--outdir", type=Path, required=True)
    parser.add_argument("--experiments", required=True)
    parser.add_argument("--display-names", default="")
    parser.add_argument("--surface-parameters", default="")
    parser.add_argument("--upper-air-parameters", default="")
    parser.add_argument("--period-type", type=int, default=1)
    parser.add_argument("--levels", default="300,500,700,850")
    args = parser.parse_args()
    try:
        return build(args)
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"scorecard staging failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
