#!/bin/ksh

. Env_exp

[[ $WEBCALL == "" ]] && exit

if [ $# -eq 1 ] ; then
   echo 
   echo "Remove all plots from $PROJECT/$1"
   echo
   $WEBCALL -e $1 -r
else
  echo 
  echo " Removed all plots from $PROJECT"
  echo 
  $WEBCALL -r
fi

echo 
echo " Your new WebgraF content"
echo 

$WEBCALL -l
