#!/bin/ksh

set -ax

. Env_exp

[[ $WEBCALL == "" ]] && exit

$WEBCALL -e Surface -r
$WEBCALL -e Surf_scat -r
$WEBCALL -e Bias_maps -r
$WEBCALL -e Precip -r
$WEBCALL -e Precip_maps -r
$WEBCALL -e Vert -r
$WEBCALL -e Temp -r
