#!/bin/bash

set -ax

. Env_exp

[[ $WEBCALL == "" ]] && exit

II="[0"
I=1

while [ $I -lt $NEXP ] ; do
   II="${II},${I}"
   I=$( expr $I + 1 )
done
II="${II}]"

#
# Surface definition file
#

cat > input.js << EOF

title = "Surface verification"

framec="Goldenrod"

v[0] = ['PS','ps','V','v','f']
t[0] = ['Timeserie stat','Timeserie','Fc length ver','Dayvar','Freq dist.']
v[1] = ['00000000']
t[1] = v[1]
v[2] = ['00000000']
t[2] = v[2]
v[3] =[1] ;
t[3] = v[3] ;
v[4] = ['calc',0,7]
t[4] = ['Wind speed','Wind dir','PMSL','T2m','Rh2m','q2m','Cloud cover','Precipitation']
v[5] =[0] ;
t[5] = v[5] ;
v[6] =[0] ;
t[6] = v[6] ;

loc = ['l','t','l','l','l','l','l']

mname = ["Type","Period","Station","dum","Parameter","Level","Exp"]
help = "${HELP}"; hide_help = false ;
pdir ="Surface/"
ext='png'
do_send = true ;

EOF

$WEBCALL -e Surface -f input.js


#
# Surface scatter definition file
#

cat > input.js << EOF
title = "Surface stations"

framec="lightcoral"


v[0] = ['s']
t[0] = ['Full scatter']
v[1] = ['00000000']
t[1] = v[1]
v[2] = ['00000000']
t[2] = v[2] ;
v[3] =  [1] ;
t[3] = v[3] ;
v[4] = ['calc',0,7]
t[4] = ['Wind speed','Wind dir','PMSL','T2m','Rh2m','q2m','Cloud cover','Precipitation']
v[5] =  [0] ;
t[5] = v[5] ;
v[6] =$II
t[6] = [$MYEXP]

mname = ["Type","Period","Station","dum","Parameter","Level","Exp"]
loc = ['l','t','l','l','l','l','l']
pdir ="Surface/"
ext='png'
help = "${HELP}"; hide_help = false ;
do_send = true ;
my_xml_txt = ['Wind speed','Wind dir','PMSL','T2m','Rh2m','q2m','Cloud cover','Precipitation']
my_xml = ['FF_00000000','DD_00000000','PS_00000000','TT_00000000','RH_00000000','QQ_00000000','NN_00000000','PE_00000000']
EOF

$WEBCALL -e Surf_scat -f input.js

#
# Bias maps
#

cat > input.js << EOF
// Input file

title = "Bias maps of surface variables"

framec="Teal"

v[0] = ['m']
t[0] = ['By time of day']
v[1] = ['b','r']
t[1] = ['Bias','Rmse']
v[2] = ['00000000']
t[2] = v[2]
v[3] = ['00000000']
t[3] = v[3] ;
v[4] =[1] ;
t[4] = v[4] ;
v[5] = ['calc',0,6]
t[5] = ['Wind speed','Wind dir','PMSL','T2m','Rh2m','q2m','Cloud cover']
v[6] =[0,1] ;
t[6] =['00UTC','12UTC']
v[7] =$II
t[7] = [$MYEXP]

mname = ["Type","Error","Period","Station","dum","Parameter","Hour","Exp"]
loc =['l','l','t','l','l','l','l','l']
pdir ="Surface/"
ext='png'
help = "${HELP}"; hide_help = false ;
do_send = true ;
EOF
$WEBCALL -e Bias_maps -f input.js

#
# Temp
#

cat > input.js << EOF
// Input file


// Input file

title = "Radiosonde verification"

framec="Lightsalmon"

v[0] = ['PS','ps','V']
t[0] = ['Timeserie stat','Timeserie','Fc length ver']
v[1] = ['00000000']
t[1] = v[1] ;
v[2] = ['00000000']
t[2] = v[2] ;
v[3] =[1] ;
t[3] = v[3] ;
v[4] = ['calc',0,5]
t[4] = ['Wind speed','Wind dir','Temperature','Relative hum','Specific hum.','Height']
v[5] = ['calc',5,0]
t[5] = [100,200,300,500,700,850]
v[6] =[0] ;
t[6] = v[6] ;

mname = ["Type","Period","Station","dum","Parameter","Level (hPa)","Exp"]

loc = ['l','t','l','l','l','l','l']
pdir ="Temp/"
ext='png'
help = "${HELP}"; hide_help = false ;
do_send = true ;
EOF

$WEBCALL -e Temp -f input.js

#
# Vert
#

cat > input.js << EOF
// Input file


// Input file

title = "Vertical temp"
framec="Tomato"

v[0] = ['l']
t[0] = ['diff']
v[1] = ['00000000']
t[1] = v[1] ;
v[2] = ['00000000']
t[2] = v[2] ;
v[3] =[1] ;
t[3] = v[3] ;
v[4] = ['calc',0,5]
t[4] = ['Wind speed','Wind dir','Temperature','Relative hum','Specific hum.','Height']
v[5] =[0] ;
t[5] =[0]
v[6] =[0] ;
t[6] =[0] ;
mname = ["Type","Period","Station","dum","Parameter","Level","Exp"]

loc = ['l','t','l','l','l','l','l']

pdir ="Vert/"
ext='png'
help = "${HELP}"; hide_help = false ;
do_send = true ;

my_xml = [
'DD0100_00000000',
'DD0200_00000000',
'DD0300_00000000',
'DD0500_00000000',
'DD0700_00000000',
'DD0850_00000000',
'FF0100_00000000',
'FF0200_00000000',
'FF0300_00000000',
'FF0500_00000000',
'FF0700_00000000',
'FF0850_00000000',
'FI0100_00000000',
'FI0200_00000000',
'FI0300_00000000',
'FI0500_00000000',
'FI0700_00000000',
'FI0850_00000000',
'QQ0100_00000000',
'QQ0200_00000000',
'QQ0300_00000000',
'QQ0500_00000000',
'QQ0700_00000000',
'QQ0850_00000000',
'RH0100_00000000',
'RH0200_00000000',
'RH0300_00000000',
'RH0500_00000000',
'RH0700_00000000',
'RH0850_00000000',
'TT0100_00000000',
'TT0200_00000000',
'TT0300_00000000',
'TT0500_00000000',
'TT0700_00000000',
'TT0850_00000000']

my_xml_txt = [
'DD0100',
'DD0200',
'DD0300',
'DD0500',
'DD0700',
'DD0850',
'FF0100',
'FF0200',
'FF0300',
'FF0500',
'FF0700',
'FF0850',
'FI0200',
'FI0300',
'FI0500',
'FI0700',
'FI0850',
'QQ0100',
'QQ0200',
'QQ0300',
'QQ0500',
'QQ0700',
'QQ0850',
'RH0200',
'RH0300',
'RH0500',
'RH0700',
'RH0850',
'TT0100',
'TT0200',
'TT0300',
'TT0500',
'TT0700',
'TT0850']
EOF

$WEBCALL -e Vert -f input.js

rm -f input.js
