#!/bin/sh
#         
#    Extract statistics from acma-file 
#

set -x

#
# link input acma file
#
ln -sf ecma_conv_${DTG} fort.10
#
# Generate namelist
#
cat  >rejstat.dat <<**EOF**
 &rejstat
    lsatob=.false.,
    lsynop=.true.,
    lmetar=.false., 
    lship=.true.,
    ldribu=.true.,
    lpilot=.true.,
    lairep=.true.,
    ltemp=.true., 
    lpreplo=.false.,
 /
**EOF**

# Run executable
$BINDIR/rejstat

