#!/bin/bash

set -a

if [ $# -eq 1 ] ; then
   ENV_EXP=$1
else
   echo "Please give an Env_exp file"
   exit 1
fi
[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }

LOGFILE=$( echo $( basename $ENV_EXP ) | sed "s/Env_exp_//" ).log

echo
echo "Output goes to $LOGFILE"
echo
set -x

./Clean_ver_js       $ENV_EXP      >  $LOGFILE 2>&1 || exit
./Run_verobs         $ENV_EXP SURF >> $LOGFILE 2>&1 || exit
./Run_verobs         $ENV_EXP TEMP >> $LOGFILE 2>&1 || exit

./Link2file          $ENV_EXP || exit
./Transport_ver      $ENV_EXP || exit

set +x

. $ENV_EXP

echo
echo "To view your result open $BASE/WebgraF/$PROJECT/index.html in your browser"
echo
