#!/bin/bash

if [ $# -eq 1 ] ; then
   ENV_EXP=$1
else
   echo "Please give an Env_exp file"
   exit 1
fi
[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }

. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
[[ $WEBCALL == "" ]] && exit 1

$WEBCALL -x

echo "Your verification results are stored in $PWD/${PROJECT}_export.tar"
echo "Copy to your local machine, untar and open ${PROJECT}_export/index.html in your browser"

$WEBCALL -t

echo "Your verification results are stored in $PWD/${PROJECT}___transport.tar"

echo
echo
echo "To view your result open $BASE/WebgraF/$PROJECT/index.html in your browser"
echo
