#!/bin/bash

if [ $# -ge 1 ] ; then
   ENV_EXP=$1
else
   echo "Please give an Env_exp file"
   exit 1
fi
[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }

. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
[[ $WEBCALL == "" ]] && exit 1

webargs=""
for arg in $*; do
  case $arg in
   "-x"|"-t")
    webargs="$webargs $arg"
  esac
done;

[[ $webargs == "" ]] && webargs="-x -t"

for arg in $webargs ; do
 $WEBCALL $arg
done 
