name: Documentation

on:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**
      
jobs:
  build:
    if: github.repository == 'Hirlam/Monitor'    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
      - name: Install Julia dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl  
